# Generated by Django 3.1.7 on 2021-06-28 05:24

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
