# Generated by Django 3.1.7 on 2021-06-29 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210628_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='next_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='app.postmodel'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='previous_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='app.postmodel'),
        ),
    ]
