# Generated by Django 3.1.7 on 2021-07-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210630_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='overview',
            field=models.CharField(max_length=250),
        ),
    ]
